export const categories = [
    { label: "Travel", value: "Travel" },
    { label: "Education", value: "Education" },
    { label: "Food", value: "Food" },
    { label: "Technology", value: "Technology" },
    { label: "Health", value: "Health" },
    { label: "Lifestyle", value: "Lifestyle" },
    { label: "Finance", value: "Finance" },
    { label: "Sports", value: "Sports" },
    { label: "Entertainment", value: "Entertainment" },
    { label: "Politics", value: "Politics" },
    { label: "Environment", value: "Environment" },
    { label: "Science", value: "Science" },
    { label: "Art", value: "Art" },
    { label: "Fashion", value: "Fashion" },
    { label: "Music", value: "Music" },
    { label: "DIY", value: "DIY" },
    { label: "Parenting", value: "Parenting" },
    { label: "Books", value: "Books" },
    { label: "Gaming", value: "Gaming" },
    { label: "History", value: "History" },
];

export const categoryColors = {
    Travel: "bg-yellow-800 text-yellow-100",
    Education: "bg-pink-800 text-pink-100",
    Food: "bg-green-800 text-green-100",
    Technology: "bg-blue-800 text-blue-100",
    Health: "bg-red-800 text-red-100",
    Lifestyle: "bg-pink-700 text-pink-100",
    Finance: "bg-teal-800 text-teal-100",
    Sports: "bg-orange-800 text-orange-100",
    Entertainment: "bg-purple-800 text-purple-100",
    Politics: "bg-gray-800 text-gray-100",
    Environment: "bg-green-700 text-green-100",
    Science: "bg-indigo-800 text-indigo-100",
    Art: "bg-purple-700 text-purple-100",
    Fashion: "bg-fuchsia-800 text-fuchsia-100",
    Music: "bg-cyan-800 text-cyan-100",
    DIY: "bg-yellow-700 text-yellow-100",
    Parenting: "bg-blue-700 text-blue-100",
    Books: "bg-emerald-800 text-emerald-100",
    Gaming: "bg-purple-800 text-purple-100",
    History: "bg-amber-800 text-amber-100",
};
